# Quantitative Value Strategy

**Author: Abraham Sobowale**

A value-investing screen over the S&P 500. In this project I rank stocks on valuation metrics (such as the price-to-earnings ratio, and a composite of several multiples) to select the cheapest names, then size an equal-weight portfolio of them.

Built from the FreeCodeCamp *Algorithmic Trading in Python* template and reworked into my own implementation.

In [2]:
import numpy as np
import pandas as pd
import requests
import math
from scipy import stats
from scipy.stats import percentileofscore as score
import xlsxwriter
from datetime import date, timedelta

## Importing Our List of Stocks & API Token

In [3]:
api_key= "UTyHVduohyBpg6IFqApjemQi7MtN1dTB"
stocks = pd.read_csv("sp_500_stocks.csv")
today = date.today()
one_year_ago = today - timedelta(days=(365))

## Making Our First API Call

In [4]:
symbol = "GM"
api_call = "https://financialmodelingprep.com/stable/company-screener?apikey=UTyHVduohyBpg6IFqApjemQi7MtN1dTB"
data = requests.get(api_call).json()
len(data)

1000

## Parsing Our API Call

In [5]:
price = data["price"]
pe_ratio = data["pe"]
pe_ratio

TypeError: list indices must be integers or slices, not str

## Executing A Batch API Call & Building Our DataFrame

In [6]:
# Function sourced from 
# https://stackoverflow.com/questions/312443/how-do-you-split-a-list-into-evenly-sized-chunks
def chunks(lst, n):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        yield lst[i:i + n]   
        
symbol_groups = list(chunks(stocks['Ticker'], 100))
symbol_strings = []
for i in range(0, len(symbol_groups)):
    symbol_strings.append(','.join(symbol_groups[i]))
#     print(symbol_strings[i])

my_columns = ['Ticker', 'Price', 'Price-to-Earnings Ratio', 'Number of Shares to Buy']

Now I need to create a blank DataFrame and add our data to the data frame one-by-one.

In [7]:
symbol_groups = list(chunks(stocks["Ticker"], 100))
symbol_str = []
for i in range(len(symbol_groups)):
    symbol_str.append(",".join(symbol_groups[i]))

final_df = pd.DataFrame(columns=my_columns)
rows = []

for symbol_s in symbol_str:
    batch_api_call_url = f"https://financialmodelingprep.com/api/v3/quote/{symbol_s}?apikey=UTyHVduohyBpg6IFqApjemQi7MtN1dTB"
    data = requests.get(batch_api_call_url).json()
    #print(data)
    for stock_data in data:  # Loop through each stock's data in the batch response
        symbol = stock_data["symbol"]  # Get the stock symbol from the response
        rows.append({
            my_columns[0]: symbol,
            my_columns[1]: stock_data["price"],
            my_columns[2]: stock_data.get("pe", "N/A"),  # Use .get() to handle missing keys
            my_columns[3]: "N/A"  # Or any default value you want
        })
    
final_df = pd.DataFrame(rows, columns=my_columns) 
final_df

    Ticker     Price  Price-to-Earnings Ratio Number of Shares to Buy
0        A  114.8000                    28.28                     N/A
1      AAL   11.2150                    13.35                     N/A
2      AAP   53.3850                    -5.49                     N/A
3     AAPL  203.9900                    28.10                     N/A
4     ABBV  196.1750                    92.97                     N/A
..     ...       ...                      ...                     ...
489    YUM  146.6200                    29.27                     N/A
490    ZBH   92.2400                    20.50                     N/A
491   ZBRA  341.6734                    32.36                     N/A
492   ZION   52.8549                     9.65                     N/A
493    ZTS  151.5898                    27.22                     N/A

[494 rows x 4 columns]

## Removing Glamour Stocks

In [8]:
final_df.sort_values("Price-to-Earnings Ratio", ascending = False, inplace = True)
final_df = final_df[final_df["Price-to-Earnings Ratio"] > 10]
final_df = final_df[:50]
final_df.reset_index(drop = True, inplace = True)
final_df

   Ticker      Price  Price-to-Earnings Ratio Number of Shares to Buy
0      DD    70.6000              2353.330000                     N/A
1     COF   209.9250               599.790000                     N/A
2     KSU   293.5900               277.495274                     N/A
3     IRM    94.9750               231.650000                     N/A
4    TWTR    53.7000               214.800000                     N/A
5     VTR    68.1050               158.380000                     N/A
6     AMD   176.8950               129.120000                     N/A
7     NOW   926.0300               116.340000                     N/A
8    AVGO   297.8320               108.700000                     N/A
9    QRVO    84.8750                99.850000                     N/A
10    UDR    38.3450                98.320000                     N/A
11   CDNS   361.7546                97.510000                     N/A
12   WELL   168.3700                93.540000                     N/A
13   ABBV   196.1750                92.970000                     N/A
14    BAX    22.4300                86.270000                     N/A
15    TYL   599.8650                85.940000                     N/A
16   EQIX   778.6309                76.410000                     N/A
17    VNO    38.6900                74.400000                     N/A
18   SNPS   631.5373                72.930000                     N/A
19   ISRG   481.2100                67.300000                     N/A
20    GLW    63.1700                67.200000                     N/A
21     WY    25.3250                66.640000                     N/A
22   ABMD   381.0200                65.355060                     N/A
23   ADSK   301.2205                64.640000                     N/A
24   INTU   788.7500                64.340000                     N/A
25    BSX   106.4600                63.370000                     N/A
26   IDXX   673.9800                62.290000                     N/A
27    LLY   762.7800                62.170000                     N/A
28    PWR   396.5500                61.580000                     N/A
29     IR    78.3400                60.730000                     N/A
30    ADI   223.1700                60.640000                     N/A
31   ALXN   182.5000                59.234015                     N/A
32   NVDA   178.9500                57.910000                     N/A
33   ORCL   251.2297                57.750000                     N/A
34    ROL    58.3150                57.740000                     N/A
35   CERN    94.9200                55.835294                     N/A
36   ANSS   374.3000                55.534125                     N/A
37    TDG  1610.9700                54.350000                     N/A
38   DXCM    76.9250                54.170000                     N/A
39   COST   952.1800                54.040000                     N/A
40    VLO   133.9700                54.020000                     N/A
41    HWM   182.4350                53.190000                     N/A
42      O    57.3350                52.120000                     N/A
43    LYV   150.9500                51.170000                     N/A
44   ANET   120.3500                50.780000                     N/A
45   CTAS   223.6450                50.710000                     N/A
46    FIS    79.1600                50.420000                     N/A
47    SYK   381.0800                50.410000                     N/A
48   NFLX  1168.9664                49.700000                     N/A
49    BEN    25.1650                49.340000                     N/A

## Calculating the Number of Shares to Buy
We now need to calculate the number of shares I need to buy. 

To do this, I will use the `portfolio_input` function that I created in our momentum project.

I have included this function below.

In [9]:
def budget():
    portfolio_size = input("What is your portfolio size? ")
    
    while True:
        try:
            val = float(portfolio_size)
            print(portfolio_size)
            break  # Exit the loop if conversion succeeds
        except ValueError:
            print("Please enter a valid number.")
            portfolio_size = input("What is your portfolio size? ")    
    return val

Use the `portfolio_input` function to accept a `portfolio_size` variable from the user of this script.

You can now use the global `portfolio_size` variable to calculate the number of shares that our strategy should purchase.

In [10]:
position_size = budget()/len(final_df.index)
for i in range(len(final_df.index)):    
    final_df["Number of Shares to Buy"] = (position_size / final_df["Price"]).apply(math.floor)
final_df

What is your portfolio size?  45431

45431

   Ticker      Price  Price-to-Earnings Ratio  Number of Shares to Buy
0      DD    70.6000              2353.330000                       12
1     COF   209.9250               599.790000                        4
2     KSU   293.5900               277.495274                        3
3     IRM    94.9750               231.650000                        9
4    TWTR    53.7000               214.800000                       16
5     VTR    68.1050               158.380000                       13
6     AMD   176.8950               129.120000                        5
7     NOW   926.0300               116.340000                        0
8    AVGO   297.8320               108.700000                        3
9    QRVO    84.8750                99.850000                       10
10    UDR    38.3450                98.320000                       23
11   CDNS   361.7546                97.510000                        2
12   WELL   168.3700                93.540000                        5
13   ABBV   196.1750                92.970000                        4
14    BAX    22.4300                86.270000                       40
15    TYL   599.8650                85.940000                        1
16   EQIX   778.6309                76.410000                        1
17    VNO    38.6900                74.400000                       23
18   SNPS   631.5373                72.930000                        1
19   ISRG   481.2100                67.300000                        1
20    GLW    63.1700                67.200000                       14
21     WY    25.3250                66.640000                       35
22   ABMD   381.0200                65.355060                        2
23   ADSK   301.2205                64.640000                        3
24   INTU   788.7500                64.340000                        1
25    BSX   106.4600                63.370000                        8
26   IDXX   673.9800                62.290000                        1
27    LLY   762.7800                62.170000                        1
28    PWR   396.5500                61.580000                        2
29     IR    78.3400                60.730000                       11
30    ADI   223.1700                60.640000                        4
31   ALXN   182.5000                59.234015                        4
32   NVDA   178.9500                57.910000                        5
33   ORCL   251.2297                57.750000                        3
34    ROL    58.3150                57.740000                       15
35   CERN    94.9200                55.835294                        9
36   ANSS   374.3000                55.534125                        2
37    TDG  1610.9700                54.350000                        0
38   DXCM    76.9250                54.170000                       11
39   COST   952.1800                54.040000                        0
40    VLO   133.9700                54.020000                        6
41    HWM   182.4350                53.190000                        4
42      O    57.3350                52.120000                       15
43    LYV   150.9500                51.170000                        6
44   ANET   120.3500                50.780000                        7
45   CTAS   223.6450                50.710000                        4
46    FIS    79.1600                50.420000                       11
47    SYK   381.0800                50.410000                        2
48   NFLX  1168.9664                49.700000                        0
49    BEN    25.1650                49.340000                       36

## Building a Better (and More Realistic) Value Strategy
Every valuation metric has certain flaws.

For example, the price-to-earnings ratio doesn't work well with stocks with negative earnings.

Similarly, stocks that buyback their own shares are difficult to value using the price-to-book ratio.

Investors typically use a `composite` basket of valuation metrics to build robust quantitative value strategies. In this section, I will filter for stocks with the lowest percentiles on the following metrics:

* Price-to-earnings ratio
* Price-to-book ratio
* Price-to-sales ratio
* Enterprise Value divided by Earnings Before Interest, Taxes, Depreciation, and Amortization (EV/EBITDA)
* Enterprise Value divided by Gross Profit (EV/GP)

Some of these metrics aren't provided directly by the IEX Cloud API, and must be computed after pulling raw data. We'll start by calculating each data point from scratch.

In [11]:
symbol_groups = list(chunks(stocks["Ticker"], 100))
symbol_str = []
for i in range(len(symbol_groups)):
    symbol_str.append(",".join(symbol_groups[i]))

comp_df = pd.DataFrame(columns=my_columns)
rows = []

for symbol_s in symbol_str:
    batch_api_call_url1 = f"https://financialmodelingprep.com/api/v3/quote/{symbol_s}?apikey={api_key}"
    batch_api_call_url2 = f"https://financialmodelingprep.com/stable/key-metrics-ttm?symbol={symbol_s}&apikey={api_key}"
    batch_api_call_url3 = f"https://financialmodelingprep.com/api/v3/balance-sheet-statement/?period=annual&apikey={api_key}"
    data1 = requests.get(batch_api_call_url1).json()
    data2 = requests.get(batch_api_call_url1).json()
    #print(data)
    for stock_data1, stock_data2 in zip(data1, data2):  # Loop through each stock's data in the batch response
        symbol = stock_data1["symbol"]  # Get the stock symbol from the response
        rows.append({
            my_columns[0]: symbol,
            my_columns[1]: stock_data1["price"],
            my_columns[2]: stock_data1.get("pe", "N/A"),  # Use .get() to handle missing keys
            my_columns[3]: "N/A"  # Or any default value you want
        })
    
comp_df = pd.DataFrame(rows, columns=my_columns) 
comp_df

Let's move on to building our DataFrame. You'll notice that I use the abbreviation `rv` often. It stands for `robust value`, which is what I'll call this sophisticated strategy moving forward.

In [49]:
data1 = "hi"
data1

'hi'

,Ticker,Price,Number of Shares to Buy,Price-to-Earnings Ratio,PE Percentile,Price-to-Book Ratio,PB Percentile,EV/EBITDA,EV/EBITDA Percentile,EV/GP,EV/GP Percentile,RV Score
0,A,100.010,N/A,46.95,N/A,6.596140,N/A,26.372976,N/A,11.311629,N/A,N/A
1,AAL,13.360,N/A,-1.71,N/A,-60.417952,N/A,5.952664,N/A,3.098483,N/A,N/A
2,AAP,161.440,N/A,29,N/A,3.123759,N/A,15.086368,N/A,3.208667,N/A,N/A
3,AAPL,466.070,N/A,34.69,N/A,22.373999,N/A,25.708773,N/A,19.428993,N/A,N/A
4,ABBV,96.680,N/A,21,N/A,-21.463532,N/A,12.272585,N/A,7.672427,N/A,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...
500,YUM,94.320,N/A,28,N/A,-3.659682,N/A,18.841249,N/A,13.891510,N/A,N/A
501,ZBH,143.470,N/A,718.1,N/A,2.390128,N/A,17.170711,N/A,7.478460,N/A,N/A
502,ZBRA,288.222,N/A,31.86,N/A,8.600669,N/A,19.480804,N/A,8.449885,N/A,N/A
503,ZION,35.770,N/A,13.24,N/A,0.766237,N/A,NaN,N/A,NaN,N/A,N/A
504,ZTS,160.920,N/A,47.2,N/A,29.222282,N/A,32.483029,N/A,19.667225,N/A,N/A

{'week52change': 0.290414, 'week52high': 169.51, 'week52low': 90.41, 'marketcap': 75861250162, 'employees': 10724, 'day200MovingAvg': 134.17, 'day50MovingAvg': 148.64, 'float': 479955020, 'avg10Volume': 1641586.3, 'avg30Volume': 1479579.2, 'ttmEPS': 3.499, 'ttmDividendRate': 0.77, 'companyName': 'Zoetis, Inc.', 'sharesOutstanding': 494883276, 'maxChangePercent': 3.3525, 'year5ChangePercent': 1.69, 'year2ChangePercent': 0.608, 'year1ChangePercent': 0.281583, 'ytdChangePercent': 0.189876, 'month6ChangePercent': 0.10241, 'month3ChangePercent': 0.297048, 'month1ChangePercent': 0.159224, 'day30ChangePercent': 0.165634, 'day5ChangePercent': -0.012817, 'nextDividendDate': None, 'dividendYield': 0.00489706569361443, 'nextEarningsDate': '2020-10-13', 'exDividendDate': '2020-07-01', 'peRatio': 49.1, 'beta': 0.9584403132945124, 'totalCash': 1974321215, 'currentDebt': 549171552, 'revenue': 6518431250, 'grossProfit': 4133660573, 'totalRevenue': 6300683466, 'EBITDA': 2502772553, 'revenuePerShare': 13.28, 'revenuePerEmployee': 618960.04, 'debtToEquity': 2.45, 'profitMargin': 0.2407740535828538, 'enterpriseValue': 81297632588, 'enterpriseValueToRevenue': 13.46, 'priceToSales': 12.6, 'priceToBook': 29.222282216073907, 'forwardPERatio': 46.68, 'pegRatio': -42.88, 'peHigh': 46.10321684721315, 'peLow': 25.052455887152025, 'week52highDate': '2020-07-31', 'week52lowDate': '2020-03-22', 'putCallRatio': 1.5877629858076678}

## Dealing With Missing Data in Our DataFrame

Our DataFrame contains some missing data because all of the metrics I require are not available through the API I'm using. 

You can use pandas' `isnull` method to identify missing data:

,Ticker,Price,Number of Shares to Buy,Price-to-Earnings Ratio,PE Percentile,Price-to-Book Ratio,PB Percentile,EV/EBITDA,EV/EBITDA Percentile,EV/GP,EV/GP Percentile,RV Score
17,AFL,39.060,N/A,9.7,N/A,0.950934,N/A,NaN,N/A,NaN,N/A,N/A
18,AIG,31.950,N/A,-5.88,N/A,0.407454,N/A,NaN,N/A,NaN,N/A,N/A
20,AIZ,127.680,N/A,20.22,N/A,1.360264,N/A,NaN,N/A,NaN,N/A,N/A
26,ALL,97.880,N/A,7.1,N/A,1.173772,N/A,NaN,N/A,NaN,N/A,N/A
39,ANTM,293.560,N/A,12.24,N/A,2.304037,N/A,NaN,N/A,NaN,N/A,N/A
40,AON,196.350,N/A,26.09,N/A,13.486066,N/A,17.533688,N/A,NaN,N/A,N/A
56,BAC,26.970,N/A,12.63,N/A,0.867662,N/A,NaN,N/A,NaN,N/A,N/A
64,BK,38.160,N/A,8.27,N/A,0.804550,N/A,NaN,N/A,NaN,N/A,N/A
65,BKNG,1866.170,N/A,30.78,N/A,12.571484,N/A,12.859665,N/A,NaN,N/A,N/A
75,C,55.140,N/A,9.52,N/A,0.576968,N/A,NaN,N/A,NaN,N/A,N/A
78,CARR,30.210,N/A,None,N/A,1.884398,N/A,9.144195,N/A,4.550543,N/A,N/A
80,CB,132.400,N/A,27.62,N/A,1.066146,N/A,NaN,N/A,NaN,N/A,N/A
90,CFG,26.840,N/A,10.71,N/A,0.501914,N/A,NaN,N/A,NaN,N/A,N/A
94,CI,188.390,N/A,13.31,N/A,1.477180,N/A,NaN,N/A,NaN,N/A,N/A
95,CINF,80.210,N/A,23.51,N/A,1.305219,N/A,NaN,N/A,NaN,N/A,N/A
97,CLX,232.200,N/A,30.25,N/A,32.278899,N/A,NaN,N/A,9.790028,N/A,N/A
98,CMA,43.270,N/A,10.2,N/A,0.801751,N/A,NaN,N/A,NaN,N/A,N/A
104,CNC,65.780,N/A,22.88,N/A,2.982878,N/A,NaN,N/A,NaN,N/A,N/A
106,COF,67.830,N/A,-195.92,N/A,0.534970,N/A,NaN,N/A,NaN,N/A,N/A
129,DFS,55.920,N/A,17.68,N/A,1.456734,N/A,NaN,N/A,NaN,N/A,N/A
185,FITB,21.043,N/A,10.87,N/A,0.717095,N/A,NaN,N/A,NaN,N/A,N/A
192,FRC,123.410,N/A,22.93,N/A,2.163006,N/A,NaN,N/A,NaN,N/A,N/A
201,GL,85.320,N/A,13.09,N/A,1.266177,N/A,NaN,N/A,NaN,N/A,N/A
210,GS,211.320,N/A,16.21,N/A,0.813961,N/A,NaN,N/A,NaN,N/A,N/A
214,HBAN,10.179,N/A,12.49,N/A,0.855431,N/A,NaN,N/A,NaN,N/A,N/A
220,HIG,42.840,N/A,8.7,N/A,0.959808,N/A,NaN,N/A,NaN,N/A,N/A
232,HUM,427.300,N/A,15.96,N/A,4.713176,N/A,NaN,N/A,NaN,N/A,N/A
260,JPM,103.310,N/A,14.29,N/A,1.213231,N/A,NaN,N/A,NaN,N/A,N/A
262,KEY,13.180,N/A,11.35,N/A,0.752496,N/A,NaN,N/A,NaN,N/A,N/A
274,L,38.130,N/A,-9.39,N/A,0.573510,N/A,NaN,N/A,NaN,N/A,N/A
285,LNC,39.000,N/A,34.14,N/A,0.382368,N/A,NaN,N/A,NaN,N/A,N/A
294,MA,326.780,N/A,46.44,N/A,57.878484,N/A,32.240726,N/A,NaN,N/A,N/A
304,MET,40.060,N/A,5.15,N/A,0.560684,N/A,NaN,N/A,NaN,N/A,N/A
310,MMC,121.870,N/A,29.5,N/A,7.745583,N/A,19.929889,N/A,NaN,N/A,N/A
318,MS,53.890,N/A,9.4,N/A,1.019241,N/A,NaN,N/A,NaN,N/A,N/A
322,MTB,109.100,N/A,10.14,N/A,0.908166,N/A,NaN,N/A,NaN,N/A,N/A
343,NTRS,84.016,N/A,13.11,N/A,1.585778,N/A,NaN,N/A,NaN,N/A,N/A
356,OTIS,65.000,N/A,None,N/A,16.466082,N/A,12.978635,N/A,7.134814,N/A,N/A
360,PBCT,11.413,N/A,9.88,N/A,0.611706,N/A,NaN,N/A,NaN,N/A,N/A
366,PFG,46.400,N/A,10,N/A,0.875822,N/A,NaN,N/A,NaN,N/A,N/A
368,PGR,91.930,N/A,11.96,N/A,3.853690,N/A,NaN,N/A,NaN,N/A,N/A
375,PNC,114.560,N/A,7,N/A,0.968309,N/A,NaN,N/A,NaN,N/A,N/A
381,PRU,69.800,N/A,-130,N/A,0.442811,N/A,NaN,N/A,NaN,N/A,N/A
391,RE,228.250,N/A,17.75,N/A,1.014116,N/A,NaN,N/A,NaN,N/A,N/A
394,RF,12.050,N/A,17.46,N/A,0.711818,N/A,NaN,N/A,NaN,N/A,N/A
410,SIVB,257.970,N/A,14.96,N/A,2.029366,N/A,NaN,N/A,NaN,N/A,N/A
421,STT,71.170,N/A,11.32,N/A,1.018320,N/A,NaN,N/A,NaN,N/A,N/A
434,TFC,39.360,N/A,12.85,N/A,0.820157,N/A,NaN,N/A,NaN,N/A,N/A
443,TRV,123.090,N/A,17.09,N/A,1.165263,N/A,NaN,N/A,NaN,N/A,N/A
458,UNH,337.050,N/A,18.69,N/A,5.428035,N/A,NaN,N/A,NaN,N/A,N/A
459,UNM,19.580,N/A,4.12,N/A,0.392314,N/A,NaN,N/A,NaN,N/A,N/A
463,USB,38.150,N/A,12.17,N/A,1.099607,N/A,NaN,N/A,NaN,N/A,N/A
482,WFC,25.670,N/A,29.3,N/A,0.566555,N/A,NaN,N/A,NaN,N/A,N/A
488,WRB,63.440,N/A,34.45,N/A,1.877291,N/A,NaN,N/A,NaN,N/A,N/A
503,ZION,35.770,N/A,13.24,N/A,0.766237,N/A,NaN,N/A,NaN,N/A,N/A

Dealing with missing data is an important topic in data science.

There are two main approaches:

* Drop missing data from the data set (pandas' `dropna` method is useful here)
* Replace missing data with a new value (pandas' `fillna` method is useful here)

In this tutorial, I will replace missing data with the average non-`NaN` data point from that column. 

Here is the code to do this:

Now, if I run the statement from earlier to print rows that contain missing data, nothing should be returned:

Empty DataFrame
Columns: [Ticker, Price, Number of Shares to Buy, Price-to-Earnings Ratio, PE Percentile, Price-to-Book Ratio, PB Percentile, EV/EBITDA, EV/EBITDA Percentile, EV/GP, EV/GP Percentile, RV Score]
Index: []

## Calculating Value Percentiles

We now need to calculate value score percentiles for every stock in the universe. More specifically, I need to calculate percentile scores for the following metrics for every stock:

* Price-to-earnings ratio
* Price-to-book ratio
* Price-to-sales ratio
* EV/EBITDA
* EV/GP

Here's how I'll do this:

0      0.841584
1      0.112871
2      0.623762
3      0.740594
4      0.427723
         ...
500         0.6
501    0.994059
502    0.693069
503    0.257426
504    0.843564
Name: PE Percentile, Length: 505, dtype: object
0       0.752475
1      0.0158416
2       0.510891
3       0.940594
4      0.0257426
         ...
500     0.049505
501     0.415842
502     0.811881
503     0.132673
504     0.956436
Name: PB Percentile, Length: 505, dtype: object
0       0.877228
1      0.0732673
2        0.50099
3       0.861386
4       0.350495
         ...
500     0.744554
501     0.572277
502     0.762376
503      0.69505
504     0.924752
Name: EV/EBITDA Percentile, Length: 505, dtype: object
0       0.552475
1      0.0574257
2      0.0653465
3       0.865347
4       0.340594
         ...
500     0.744554
501     0.326733
502          0.4
503     0.644554
504     0.869307
Name: EV/GP Percentile, Length: 505, dtype: object

,Ticker,Price,Number of Shares to Buy,Price-to-Earnings Ratio,PE Percentile,Price-to-Book Ratio,PB Percentile,EV/EBITDA,EV/EBITDA Percentile,EV/GP,EV/GP Percentile,RV Score
0,A,100.010,N/A,46.95,0.841584,6.596140,0.752475,26.372976,0.877228,11.311629,0.552475,N/A
1,AAL,13.360,N/A,-1.71,0.112871,-60.417952,0.0158416,5.952664,0.0732673,3.098483,0.0574257,N/A
2,AAP,161.440,N/A,29.00,0.623762,3.123759,0.510891,15.086368,0.50099,3.208667,0.0653465,N/A
3,AAPL,466.070,N/A,34.69,0.740594,22.373999,0.940594,25.708773,0.861386,19.428993,0.865347,N/A
4,ABBV,96.680,N/A,21.00,0.427723,-21.463532,0.0257426,12.272585,0.350495,7.672427,0.340594,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...
500,YUM,94.320,N/A,28.00,0.6,-3.659682,0.049505,18.841249,0.744554,13.891510,0.744554,N/A
501,ZBH,143.470,N/A,718.10,0.994059,2.390128,0.415842,17.170711,0.572277,7.478460,0.326733,N/A
502,ZBRA,288.222,N/A,31.86,0.693069,8.600669,0.811881,19.480804,0.762376,8.449885,0.4,N/A
503,ZION,35.770,N/A,13.24,0.257426,0.766237,0.132673,18.729176,0.69505,12.206556,0.644554,N/A
504,ZTS,160.920,N/A,47.20,0.843564,29.222282,0.956436,32.483029,0.924752,19.667225,0.869307,N/A

## Calculating the RV Score
We'll now calculate our RV Score (which stands for Robust Value), which is the value score that I'll use to filter for stocks in this investing strategy.

The RV Score will be the arithmetic mean of the 4 percentile scores that I calculated in the last section.

To calculate arithmetic mean, I will use the mean function from Python's built-in statistics module.

,Ticker,Price,Number of Shares to Buy,Price-to-Earnings Ratio,PE Percentile,Price-to-Book Ratio,PB Percentile,EV/EBITDA,EV/EBITDA Percentile,EV/GP,EV/GP Percentile,RV Score
0,A,100.010,N/A,46.95,0.841584,6.596140,0.752475,26.372976,0.877228,11.311629,0.552475,0.755941
1,AAL,13.360,N/A,-1.71,0.112871,-60.417952,0.0158416,5.952664,0.0732673,3.098483,0.0574257,0.0648515
2,AAP,161.440,N/A,29.00,0.623762,3.123759,0.510891,15.086368,0.50099,3.208667,0.0653465,0.425248
3,AAPL,466.070,N/A,34.69,0.740594,22.373999,0.940594,25.708773,0.861386,19.428993,0.865347,0.85198
4,ABBV,96.680,N/A,21.00,0.427723,-21.463532,0.0257426,12.272585,0.350495,7.672427,0.340594,0.286139
...,...,...,...,...,...,...,...,...,...,...,...,...
500,YUM,94.320,N/A,28.00,0.6,-3.659682,0.049505,18.841249,0.744554,13.891510,0.744554,0.534653
501,ZBH,143.470,N/A,718.10,0.994059,2.390128,0.415842,17.170711,0.572277,7.478460,0.326733,0.577228
502,ZBRA,288.222,N/A,31.86,0.693069,8.600669,0.811881,19.480804,0.762376,8.449885,0.4,0.666832
503,ZION,35.770,N/A,13.24,0.257426,0.766237,0.132673,18.729176,0.69505,12.206556,0.644554,0.432426
504,ZTS,160.920,N/A,47.20,0.843564,29.222282,0.956436,32.483029,0.924752,19.667225,0.869307,0.898515

## Selecting the 50 Best Value Stocks¶

As before, I can identify the 50 best value stocks in our universe by sorting the DataFrame on the RV Score column and dropping all but the top 50 entries.

## Calculating the Number of Shares to Buy
We'll use the `portfolio_input` function that I created earlier to accept our portfolio size. Then I will use similar logic in a for loop to calculate the number of shares to buy for each stock in our investment universe.

Enter the value of your portfolio:1000000

,Ticker,Price,Number of Shares to Buy,Price-to-Earnings Ratio,PE Percentile,Price-to-Book Ratio,PB Percentile,EV/EBITDA,EV/EBITDA Percentile,EV/GP,EV/GP Percentile,RV Score
0,HPE,9.830,1994,-293.68,0.0118812,0.768699,0.134653,4.757379,0.0455446,2.575722,0.039604,0.0579208
1,FTI,8.870,2210,-0.68,0.134653,0.526579,0.0732673,2.722313,0.00792079,1.745265,0.0178218,0.0584158
2,AAL,13.360,1467,-1.71,0.112871,-60.417952,0.0158416,5.952664,0.0732673,3.098483,0.0574257,0.0648515
3,CCL,15.610,1256,-3.90,0.10297,0.380999,0.0554455,3.751649,0.0237624,3.458441,0.0811881,0.0658416
4,HFC,25.660,764,-26.18,0.0435644,0.716944,0.120792,3.301222,0.0118812,3.693071,0.0891089,0.0663366
5,HPQ,19.140,1024,9.17,0.172277,-23.323972,0.0237624,5.822424,0.0673267,2.516859,0.0356436,0.0747525
6,XRX,17.800,1101,9.35,0.174257,0.640297,0.0990099,3.620185,0.019802,1.604068,0.0138614,0.0767327
7,TPR,16.010,1224,-20.58,0.049505,1.200922,0.231683,3.870569,0.029703,1.149885,0.0019802,0.0782178
8,LB,27.330,717,-10.49,0.0633663,-5.047485,0.0455446,8.144139,0.170297,3.119623,0.0613861,0.0851485
9,SYF,25.300,775,7.77,0.152475,0.971730,0.180198,2.129599,0.0039604,1.604512,0.0158416,0.0881188
10,TAP,39.340,498,-52.36,0.0356436,0.578118,0.0891089,7.089363,0.108911,4.272303,0.120792,0.0886139
11,NWS,15.981,1226,-7.49,0.0752475,0.414744,0.0653465,8.449938,0.190099,2.998177,0.0514851,0.0955446
12,UAL,36.500,537,-5.93,0.0891089,0.931935,0.170297,3.812066,0.0277228,4.040411,0.10495,0.0980198
13,IVZ,10.900,1798,10.63,0.19802,0.371514,0.0534653,6.906037,0.10297,2.917683,0.0475248,0.100495
14,COTY,4.270,4592,-1.07,0.122772,0.699648,0.112871,7.926827,0.148515,2.045210,0.0277228,0.10297
15,DAL,29.300,669,-5.14,0.0970297,1.266128,0.243564,3.522233,0.0178218,3.119418,0.0594059,0.104455
16,DISCA,22.700,863,9.60,0.180198,0.363484,0.0514851,5.844247,0.0693069,4.354043,0.124752,0.106436
17,PVH,56.280,348,-5.12,0.0990099,0.664241,0.10297,9.261763,0.223762,1.476319,0.0118812,0.109406
18,BKR,17.780,1102,-1.10,0.120792,0.537604,0.0792079,7.481882,0.122772,4.347533,0.122772,0.111386
19,BEN,22.480,872,10.95,0.205941,1.127782,0.217822,3.458549,0.0138614,1.475177,0.00990099,0.111881
20,NWSA,15.300,1281,-7.31,0.0772277,0.802438,0.140594,8.385668,0.186139,2.917670,0.0455446,0.112376
21,DISCK,21.080,930,9.11,0.168317,0.706494,0.116832,5.620235,0.0594059,4.154303,0.112871,0.114356
22,NCLH,15.590,1257,-1.68,0.114851,0.660699,0.10099,6.134222,0.0851485,5.089065,0.182178,0.120792
23,MRO,6.030,3251,-7.26,0.0792079,0.386172,0.0594059,3.135953,0.00990099,7.809283,0.346535,0.123762
24,MPC,37.350,524,-3.23,0.106931,0.733937,0.126733,5.509754,0.0554455,5.622738,0.215842,0.126238
25,DXC,20.160,972,-0.87,0.130693,1.088626,0.205941,4.093135,0.0356436,4.734496,0.158416,0.132673
26,MHK,92.450,212,13.45,0.265347,0.787058,0.136634,6.000217,0.0772277,3.333651,0.0693069,0.137129
27,GPS,15.440,1269,-7.10,0.0831683,1.721678,0.316832,7.537870,0.128713,1.919594,0.0257426,0.138614
28,VIAC,27.563,711,13.15,0.255446,1.126636,0.215842,2.049573,0.0019802,3.621115,0.0871287,0.140099
29,FANG,45.280,433,-2.64,0.108911,0.532947,0.0752475,4.236347,0.0415842,7.856301,0.350495,0.144059
30,WDC,36.370,539,-43.31,0.0376238,1.190996,0.227723,8.742497,0.19802,4.502085,0.134653,0.149505
31,WRK,30.710,638,10.03,0.190099,0.690004,0.108911,6.021276,0.0831683,5.745581,0.219802,0.150495
32,CTL,11.220,1747,9.80,0.184158,0.912656,0.168317,5.277040,0.0534653,6.042985,0.239604,0.161386
33,FOX,26.460,741,16.41,0.328713,0.676120,0.10495,6.950444,0.10495,4.414420,0.126733,0.166337
34,RCL,60.600,323,-6.41,0.0871287,1.033061,0.194059,7.174071,0.110891,6.567250,0.275248,0.166832
35,UA,9.830,1994,-6.49,0.0851485,1.060941,0.19604,12.701717,0.362376,2.100650,0.029703,0.168317
36,SCHW,36.250,540,15.11,0.306931,2.069167,0.372277,2.325805,0.00594059,1.220535,0.0039604,0.172277
37,EXPE,88.450,221,-8.06,0.0712871,3.056182,0.50297,7.267947,0.114851,1.456282,0.00792079,0.174257
38,UAA,11.140,1760,-7.52,0.0732673,0.988515,0.184158,13.812802,0.433663,2.184035,0.0316832,0.180693
39,FOXA,25.740,761,16.35,0.326733,0.880273,0.164356,6.900888,0.10099,4.540753,0.136634,0.182178
40,VNO,35.870,546,21.49,0.431683,1.072895,0.20396,3.485153,0.0158416,3.603223,0.0831683,0.183663
41,DVN,12.040,1628,-1.49,0.116832,0.820986,0.148515,4.098153,0.0376238,9.447806,0.455446,0.189604
42,NWL,17.834,1099,-7.13,0.0811881,1.484674,0.285149,10.817287,0.277228,4.190990,0.114851,0.189604
43,WU,24.380,804,16.04,0.316832,-244.906130,0.00792079,9.080150,0.213861,6.028085,0.237624,0.194059
44,CVS,66.200,296,10.61,0.19604,1.353402,0.263366,9.882833,0.241584,3.620672,0.0851485,0.196535
45,MGM,22.160,884,5.59,0.146535,1.406820,0.275248,8.075014,0.162376,5.754476,0.221782,0.201485
46,PSX,64.660,303,-23.44,0.0475248,1.148756,0.219802,8.790870,0.20198,7.691650,0.342574,0.20297
47,NI,24.830,789,-80.23,0.0316832,1.587958,0.30099,9.177249,0.219802,6.421577,0.267327,0.20495
48,CXO,52.680,372,-1.06,0.125743,0.582959,0.0910891,5.069334,0.0514851,11.573139,0.566337,0.208663
49,NLSN,16.140,1214,-9.03,0.0673267,2.590361,0.457426,8.050020,0.160396,4.710304,0.152475,0.209406
50,HWM,17.680,N/A,14.73,0.29901,1.738266,0.320792,5.696284,0.0613861,5.228678,0.192079,0.218317