In [2]:
import numpy as np
import pandas as pd
import requests
import math
from scipy import stats
from scipy.stats import percentileofscore as score
import xlsxwriter
from datetime import date, timedelta
import json

In [3]:
stocks = pd.read_csv("sp_500_stocks.csv")

In [4]:
api_key= "UTyHVduohyBpg6IFqApjemQi7MtN1dTB"

In [9]:
symbol = "^GSPC"
today = date.today()
one_year_ago = today - timedelta(days=((365*10)))
api_url = f"https://financialmodelingprep.com/api/v3/historical-price-full/{symbol}?from={one_year_ago}&to={today}&apikey={api_key}"
data = requests.get(api_url).json()

In [10]:
sp500 = pd.DataFrame(data['historical'])

sp500 

# 3. Process the DataFrame for better usability (optional but recommended)
sp500['date'] = pd.to_datetime(sp500['date']) # Convert 'date' column to datetime objects
sp500.set_index('date', inplace=True)      # Set the 'date' column as the index
sp500 = sp500.iloc[::-1]      # Reverses the order
del sp500['adjClose']
del sp500['unadjustedVolume']
del sp500['label']
sp500

,open,high,low,close,volume,change,changePercent,vwap,changeOverTime
date,,,,,,,,,
2015-08-17,2089.70,2102.87,2079.30,2102.44,2867690000,12.74,0.609660,2094.8700,0.006097
2015-08-18,2101.99,2103.47,2094.14,2096.92,2949990000,-5.07,-0.241200,2098.1800,-0.002412
2015-08-19,2095.69,2096.17,2070.53,2079.61,3512920000,-16.08,-0.767290,2082.1000,-0.007673
2015-08-20,2076.61,2076.61,2035.73,2035.73,3922470000,-40.88,-1.970000,2049.3600,-0.019700
2015-08-21,2034.08,2034.08,1970.89,1970.89,5018240000,-63.19,-3.110000,1991.9500,-0.031100
...,...,...,...,...,...,...,...,...,...
2025-08-07,6379.43,6389.71,6310.32,6339.99,5306090000,-39.44,-0.618240,6354.8625,-0.006182
2025-08-08,6355.22,6395.16,6355.22,6389.44,4769910000,34.22,0.538460,6373.7600,0.005385
2025-08-11,6389.67,6407.25,6364.06,6373.46,4652400000,-16.21,-0.253690,6383.6100,-0.002537
2025-08-12,6395.17,6446.55,6385.76,6445.75,5135300000,50.58,0.790910,6418.3075,0.007909
2025-08-13,6462.67,6480.28,6445.02,6461.04,2122175000,-1.63,-0.025222,6462.1100,-0.000252

In [11]:
sp500["Tomorrow"] = sp500["close"].shift(-1)
sp500

,open,high,low,close,volume,change,changePercent,vwap,changeOverTime,Tomorrow
date,,,,,,,,,,
2015-08-17,2089.70,2102.87,2079.30,2102.44,2867690000,12.74,0.609660,2094.8700,0.006097,2096.92
2015-08-18,2101.99,2103.47,2094.14,2096.92,2949990000,-5.07,-0.241200,2098.1800,-0.002412,2079.61
2015-08-19,2095.69,2096.17,2070.53,2079.61,3512920000,-16.08,-0.767290,2082.1000,-0.007673,2035.73
2015-08-20,2076.61,2076.61,2035.73,2035.73,3922470000,-40.88,-1.970000,2049.3600,-0.019700,1970.89
2015-08-21,2034.08,2034.08,1970.89,1970.89,5018240000,-63.19,-3.110000,1991.9500,-0.031100,1893.21
...,...,...,...,...,...,...,...,...,...,...
2025-08-07,6379.43,6389.71,6310.32,6339.99,5306090000,-39.44,-0.618240,6354.8625,-0.006182,6389.44
2025-08-08,6355.22,6395.16,6355.22,6389.44,4769910000,34.22,0.538460,6373.7600,0.005385,6373.46
2025-08-11,6389.67,6407.25,6364.06,6373.46,4652400000,-16.21,-0.253690,6383.6100,-0.002537,6445.75
2025-08-12,6395.17,6446.55,6385.76,6445.75,5135300000,50.58,0.790910,6418.3075,0.007909,6461.04
2025-08-13,6462.67,6480.28,6445.02,6461.04,2122175000,-1.63,-0.025222,6462.1100,-0.000252,NaN

In [12]:
sp500["Target"] = (sp500["Tomorrow"] > sp500["close"]).astype(int)
sp500

,open,high,low,close,volume,change,changePercent,vwap,changeOverTime,Tomorrow,Target
date,,,,,,,,,,,
2015-08-17,2089.70,2102.87,2079.30,2102.44,2867690000,12.74,0.609660,2094.8700,0.006097,2096.92,0
2015-08-18,2101.99,2103.47,2094.14,2096.92,2949990000,-5.07,-0.241200,2098.1800,-0.002412,2079.61,0
2015-08-19,2095.69,2096.17,2070.53,2079.61,3512920000,-16.08,-0.767290,2082.1000,-0.007673,2035.73,0
2015-08-20,2076.61,2076.61,2035.73,2035.73,3922470000,-40.88,-1.970000,2049.3600,-0.019700,1970.89,0
2015-08-21,2034.08,2034.08,1970.89,1970.89,5018240000,-63.19,-3.110000,1991.9500,-0.031100,1893.21,0
...,...,...,...,...,...,...,...,...,...,...,...
2025-08-07,6379.43,6389.71,6310.32,6339.99,5306090000,-39.44,-0.618240,6354.8625,-0.006182,6389.44,1
2025-08-08,6355.22,6395.16,6355.22,6389.44,4769910000,34.22,0.538460,6373.7600,0.005385,6373.46,0
2025-08-11,6389.67,6407.25,6364.06,6373.46,4652400000,-16.21,-0.253690,6383.6100,-0.002537,6445.75,1
2025-08-12,6395.17,6446.55,6385.76,6445.75,5135300000,50.58,0.790910,6418.3075,0.007909,6461.04,1
2025-08-13,6462.67,6480.28,6445.02,6461.04,2122175000,-1.63,-0.025222,6462.1100,-0.000252,NaN,0

In [13]:
len(sp500)

2513

In [35]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, class_weight="balanced", min_samples_split=2, random_state=67) 
# 1:4 ratio
trainsize = math.floor(len(sp500) / 5) 
#trainsize = 100
print(trainsize)
train = sp500.iloc[:trainsize]
test = sp500.iloc[(-4*trainsize):]
# can't overlap to prevent cross-validation
predictors = ["close", "volume", "open", "high", "low", "changePercent","vwap"]
model.fit(train[predictors], train["Target"])

502

RandomForestClassifier(class_weight='balanced', random_state=67)

In [36]:
from sklearn.metrics import precision_score

preds = model.predict(test[predictors])
preds = pd.Series(preds, index=test.index)
precision_score(test["Target"], preds)

0.5882352941176471

In [37]:
def predict(train, test, predictors, model):
    model.fit(train[predictors], train["Target"])
    preds = model.predict(test[predictors])
    preds = pd.Series(preds, index=test.index, name="Predictions")
    combined = pd.concat([test["Target"], preds], axis=1)
    return combined

In [41]:
def backtest(data, model, predictors, start=2500, step=100):
    all_predictions = []

    for i in range(start, data.shape[0], step):
        train = data.iloc[0:i].copy()
        test = data.iloc[i:(i+step)].copy()
        predictions = predict(train, test, predictors, model)
        all_predictions.append(predictions)
    
    return pd.concat(all_predictions)

In [42]:
predictions = backtest(sp500, model, predictors)

In [43]:
precision_score(predictions["Target"], predictions["Predictions"])

0.4166666666666667

In [27]:
datas

[{'symbol': 'SPY',
  'publishedDate': '2025-07-31 09:34:23',
  'title': 'NASDAQ Index, S&P 500 and Dow Jones Forecasts – US Indices Continue to Look Upwards',
  'image': 'https://images.financialmodelingprep.com/news/nasdaq-index-sp-500-and-dow-jones-forecasts-us-20250731.jpg',
  'site': 'fxempire.com',
  'text': 'The three major US indices all look as if they are going to continue to look to higher levels, although there are differing signs of momentum or strength.',
  'url': 'https://www.fxempire.com/forecasts/article/nasdaq-index-sp-500-and-dow-jones-forecasts-us-indices-continue-to-look-upwards-1537769'},
 {'symbol': 'SPY',
  'publishedDate': '2025-07-31 08:24:15',
  'title': 'How To Trade SPY, Top Tech Stocks Using Technical Analysis',
  'image': 'https://images.financialmodelingprep.com/news/how-to-trade-spy-top-tech-stocks-using-technical-20250731.jpg',
  'site': 'benzinga.com',
  'text': 'Good Morning Traders!',
  'url': 'https://www.benzinga.com/markets/equities/25/07/46754137/how-to-trade-spy-top-tech-stocks-using-technical-analysis'},
 {'symbol': 'SPY',
  'publishedDate': '2025-07-31 08:00:04',
  'title': 'Can the S&P 500 Rally Overcome Bearish Seasonality?',
  'image': 'https://images.financialmodelingprep.com/news/can-the-sp-500-rally-overcome-bearish-seasonality-20250731.jpg',
  'site': 'schaeffersresearch.com',
  'text': 'As we head into August, the S&P 500 Index (SPX) is on a three-month win streak, gaining about 14% over that span.',
  'url': 'https://www.schaeffersresearch.com/content/analysis/2025/07/31/can-the-s-p-500-rally-overcome-bearish-seasonality'},
 {'symbol': 'SPY',
  'publishedDate': '2025-07-31 04:20:00',
  'title': 'Stock Market Today: S&P 500 Futures Rise After Flurry of Trade Deals, Earnings',
  'image': 'https://images.financialmodelingprep.com/news/stock-market-today-sp-500-futures-rise-after-flurry-20250731.jpg',
  'site': 'wsj.com',
  'text': 'U.S. and South Korea agree to a trade pact that will see the U.S. apply 15% tariffs',
  'url': 'https://www.wsj.com/livecoverage/stock-market-today-dow-sp-500-nasdaq-07-31-2025-2'},
 {'symbol': 'SPY',
  'publishedDate': '2025-07-31 03:50:00',
  'title': 'Stock Market Today: Flurry of Trade Deals Boosts Dow, S&P 500 Futures',
  'image': 'https://images.financialmodelingprep.com/news/stock-market-today-flurry-of-trade-deals-boosts-dow-20250731.jpg',
  'site': 'wsj.com',
  'text': 'U.S. and South Korea agree to a trade pact that will see the U.S. apply 15% tariffs',
  'url': 'https://www.wsj.com/livecoverage/stock-market-today-dow-sp-500-nasdaq-07-31-2025'},
 {'symbol': 'SPY',
  'publishedDate': '2025-07-30 16:14:52',
  'title': 'YLDE: A Dividend ETF That Writes Options Against The S&P 500',
  'image': 'https://images.financialmodelingprep.com/news/ylde-a-dividend-etf-that-writes-options-against-the-20250730.jpg',
  'site': 'seekingalpha.com',
  'text': "YLDE offers diversified exposure to high-quality dividend growth companies and monthly payouts, simplifying income investing for those seeking steady cash flow. The ETF's option-writing strategy on the S&P 500 aims to boost income, but caps price appreciation and leads to underperformance versus traditional index ETFs. Dividend yield is modest at 3.2% and payouts are inconsistent, with tax efficiency concerns making YLDE best suited for tax-advantaged accounts.",
  'url': 'https://seekingalpha.com/article/4806339-ylde-a-dividend-etf-that-writes-options-against-the-s-and-p-500'},
 {'symbol': 'SPY',
  'publishedDate': '2025-07-30 15:19:08',
  'title': 'Wall Street bull boosts his S&P 500 target to 7,100',
  'image': 'https://images.financialmodelingprep.com/news/wall-street-bull-boosts-his-sp-500-target-to-20250730.jpg',
  'site': 'youtube.com',
  'text': 'Oppenheimer & Co. Inc. chief investment strategist John Stoltzfus is the biggest bull on Wall Street. He had a year-end target of 7,100 for the S&P 500 (^GSPC), a street high.',
  'url': 'https://www.youtube.com/watch?v=-4X8qMBN9-M'},
 {'symbol': 'SPY',
  'publishedDate': '2025-07-30 14:36:00',
  'title': 'UPS Stock Joins 7% Yielders in S&P 500. Who Else Is in the Club.',
  'image': 'https://images.financialmodelingprep.com/news/ups-stock-joins-7-yielders-in-sp-500-who-20250730.jpg',
  'site': 'barrons.com',
  'text': 'There are now five stocks in the index with 7%-plus yields.',
  'url': 'https://www.barrons.com/articles/ups-stock-yield-earnings-s-p-500-a18ce93d'},
 {'symbol': 'SPY',
  'publishedDate': '2025-07-30 14:25:00',
  'title': "Is another S&P 500 change on the horizon? Here's what to know.",
  'image': 'https://images.financialmodelingprep.com/news/is-another-sp-500-change-on-the-horizon-heres-20250730.jpg',
  'site': 'marketwatch.com',
  'text': 'The Paramount-Skydance deal could open the door for a membership change, but Robinhood and AppLovin may once again miss out on inclusion in the index.',
  'url': 'https://www.marketwatch.com/story/is-another-s-p-500-change-on-the-horizon-heres-what-to-know-dacea437'},
 {'symbol': 'SPY',
  'publishedDate': '2025-07-30 11:31:03',
  'title': 'EWU: Why UK Stocks Could Beat The S&P 500 The Next 3-5 Years',
  'image': 'https://images.financialmodelingprep.com/news/ewu-why-uk-stocks-could-beat-the-sp-500-20250730.jpg',
  'site': 'seekingalpha.com',
  'text': 'EWU offers a compelling relative value versus SPY, with attractive valuation, higher dividend yield, and other relatively strong features versus the S&P 500. The UK market, via EWU, is less exposed to tech concentration risk than the S&P 500, making it a useful hedge in uncertain times. Currency trends and global macro shifts could favor non-US equities like EWU over the next 3-5 years, especially if the US dollar weakens.',
  'url': 'https://seekingalpha.com/article/4806067-ewu-why-uk-stocks-could-beat-the-s-and-p-500-the-next-3-5-years'},
 {'symbol': 'SPY',
  'publishedDate': '2025-07-30 10:10:35',
  'title': 'NASDAQ Index, S&P 500 and Dow Jones Forecasts – US Indices Wait for Jerome Powell',
  'image': 'https://images.financialmodelingprep.com/news/nasdaq-index-sp-500-and-dow-jones-forecasts-us-20250730.jpg',
  'site': 'fxempire.com',
  'text': 'The three major US indices are simply waiting for the FOMC interest rate decision, and of course the press conference and statement. With this, the market still looks bullish longer-term.',
  'url': 'https://www.fxempire.com/forecasts/article/nasdaq-index-sp-500-and-dow-jones-forecasts-us-indices-wait-for-jerome-powell-2-1537523'},
 {'symbol': 'SPY',
  'publishedDate': '2025-07-30 10:05:00',
  'title': 'S&P 500 inches up on strong GDP; Microsoft, Meta earnings ahead',
  'image': 'https://images.financialmodelingprep.com/news/sp-500-inches-up-on-strong-gdp-microsoft-meta-20250730.jpg',
  'site': 'proactiveinvestors.com',
  'text': '9:55am: Cautious start Markets opened little changed on Wednesday as investors took in a stronger-than-expected rebound in economic growth and braced for a key Federal Reserve interest rate decision later in the day. The Dow Jones was flat, up just 3 points to 44,636, while the S&P 500 edged up 5 points, or 0.1%, to 6,376.',
  'url': 'https://www.proactiveinvestors.com/companies/news/1075742'},
 {'symbol': 'SPY',
  'publishedDate': '2025-07-30 07:55:50',
  'title': 'State Street Gives Sector Investors an Income Boost',
  'image': 'https://images.financialmodelingprep.com/news/state-street-gives-sector-investors-an-income-boost-20250730.jpg',
  'site': 'etftrends.com',
  'text': 'The S&P 500 hit record highs multiple times in late July 2025. While investors seeking capital appreciation should be thrilled, those wanting income from their equity investments are likely a little disappointed.',
  'url': 'https://www.etftrends.com/state-street-gives-sector-investors-income-boost/'},
 {'symbol': 'SPY',
  'publishedDate': '2025-07-30 06:26:54',
  'title': 'SPXL: A Good Option For Investors Looking To Amplify Gains From The S&P 500 - With Risks',
  'image': 'https://images.financialmodelingprep.com/news/spxl-a-good-option-for-investors-looking-to-amplify-20250730.jpg',
  'site': 'seekingalpha.com',
  'text': 'SPXL offers 3x daily leveraged exposure to the S&P 500, best suited for short-term tactical trades around major market catalysts. Key bullish drivers include surging AI investment, positive trade deals, and potential Fed rate cuts, all of which could spark sharp market moves. Leveraged ETFs like SPXL amplify both gains and losses, with volatility and loss recoupment risks making them unsuitable for long-term holding.',
  'url': 'https://seekingalpha.com/article/4805923-spxl-a-good-option-for-investors-looking-to-amplify-gains-from-the-s-and-p-500-with-risks'},
 {'symbol': 'SPY',
  'publishedDate': '2025-07-29 12:01:18',
  'title': "5 ETFs With Big Inflows Last Week on S&P 500's Record Rally",
  'image': 'https://images.financialmodelingprep.com/news/5-etfs-with-big-inflows-last-week-on-sp-20250729.jpg',
  'site': 'zacks.com',
  'text': 'VOO, VXUS, GLD, SPY and DYNF led ETF inflows last week as the S&P 500 hit five straight record closes.',
  'url': 'https://www.zacks.com/stock/news/2634169/5-etfs-with-big-inflows-last-week-on-s-p-500-s-record-rally?cid=CS-STOCKNEWSAPI-FT-etf_news_and_commentary-2634169'},
 {'symbol': 'SPY',
  'publishedDate': '2025-07-29 09:57:44',
  'title': 'How To Trade SPY, Top Tech Stocks Using Technical Analysis',
  'image': 'https://images.financialmodelingprep.com/news/how-to-trade-spy-top-tech-stocks-using-technical-20250729.jpg',
  'site': 'benzinga.com',
  'text': 'Good Morning Traders!',
  'url': 'https://www.benzinga.com/markets/equities/25/07/46689164/how-to-trade-spy-top-tech-stocks-using-technical-analysis'},
 {'symbol': 'SPY',
  'publishedDate': '2025-07-29 09:31:21',
  'title': 'NASDAQ Index, S&P 500 and Dow Jones Forecasts – US Indices Look Forward to Fed Meeting',
  'image': 'https://images.financialmodelingprep.com/news/nasdaq-index-sp-500-and-dow-jones-forecasts-us-20250729.jpg',
  'site': 'fxempire.com',
  'text': "The three major US indices are looking forward to the FOMC Meeting on Wednesday, as the interest rate decision probably won't be a change, but the statement and press conference will be paramount as far as moving forward is concerned.",
  'url': 'https://www.fxempire.com/forecasts/article/nasdaq-index-sp-500-and-dow-jones-forecasts-us-indices-look-forward-to-fed-meeting-1537199'},
 {'symbol': 'SPY',
  'publishedDate': '2025-07-29 03:59:00',
  'title': 'Stock Market Today: S&P 500 Futures Edge Up and Dollar Gains; Focus Turns to Earnings',
  'image': 'https://images.financialmodelingprep.com/news/stock-market-today-sp-500-futures-edge-up-and-20250729.jpg',
  'site': 'wsj.com',
  'text': 'U.S. and Chinese officials are due to convene in Stockholm for a second day of trade talks',
  'url': 'https://www.wsj.com/livecoverage/stock-market-today-dow-sp500-nasdaq-07-29-2025'},
 {'symbol': 'SPY',
  'publishedDate': '2025-07-28 23:36:36',
  'title': 'Bitcoin is the S&P 500 of the future, and will top $200K this year: Expert',
  'image': 'https://images.financialmodelingprep.com/news/bitcoin-is-the-sp-500-of-the-future-and-20250728.jpg',
  'site': 'youtube.com',
  'text': "Jordi Visser of 22V Research shares his bullish call for Bitcoin, the convergence between AI and cryptocurrencies, plus what's next for stablecoins.",
  'url': 'https://www.youtube.com/watch?v=lVUbcv8MuzM'},
 {'symbol': 'SPY',
  'publishedDate': '2025-07-28 18:02:06',
  'title': 'S&P 500 notches record close, DOJ to crack down on tariff violators',
  'image': 'https://images.financialmodelingprep.com/news/sp-500-notches-record-close-doj-to-crack-down-20250728.jpg',
  'site': 'youtube.com',
  'text': "Market Domination Overtime anchor Josh Lipton breaks down the day's stock news for July 28, 2025. The S&P 500 notched another record close following the US-EU trade framework announcement.",
  'url': 'https://www.youtube.com/watch?v=O4cCw22QRSA'}]

In [29]:
if datas and isinstance(datas, list): # Check if we got a list of data
    # This is the key step: convert the list of dictionaries to a DataFrame
    df = pd.DataFrame(datas)

    # 3. Best Practices: Clean & Refine the DataFrame
    # ===============================================
    
    # Convert the 'publishedDate' column to a proper datetime format
    df['publishedDate'] = pd.to_datetime(df['publishedDate'])

    # Set the 'publishedDate' as the index for easier time-series analysis
    df.set_index('publishedDate', inplace=True)
    
    # Sort by date, just in case the API doesn't return it sorted
    df.sort_index(ascending=False, inplace=True)

    # Optionally, select only the columns you need
    df_clean = df[['symbol', 'title', 'site', 'url']]

df_clean

,symbol,title,site,url
publishedDate,,,,
2025-07-31 09:34:23,SPY,"NASDAQ Index, S&P 500 and Dow Jones Forecasts ...",fxempire.com,https://www.fxempire.com/forecasts/article/nas...
2025-07-31 08:24:15,SPY,"How To Trade SPY, Top Tech Stocks Using Techni...",benzinga.com,https://www.benzinga.com/markets/equities/25/0...
2025-07-31 08:00:04,SPY,Can the S&P 500 Rally Overcome Bearish Seasona...,schaeffersresearch.com,https://www.schaeffersresearch.com/content/ana...
2025-07-31 04:20:00,SPY,Stock Market Today: S&P 500 Futures Rise After...,wsj.com,https://www.wsj.com/livecoverage/stock-market-...
2025-07-31 03:50:00,SPY,Stock Market Today: Flurry of Trade Deals Boos...,wsj.com,https://www.wsj.com/livecoverage/stock-market-...
2025-07-30 16:14:52,SPY,YLDE: A Dividend ETF That Writes Options Again...,seekingalpha.com,https://seekingalpha.com/article/4806339-ylde-...
2025-07-30 15:19:08,SPY,Wall Street bull boosts his S&P 500 target to ...,youtube.com,https://www.youtube.com/watch?v=-4X8qMBN9-M
2025-07-30 14:36:00,SPY,UPS Stock Joins 7% Yielders in S&P 500. Who El...,barrons.com,https://www.barrons.com/articles/ups-stock-yie...
2025-07-30 14:25:00,SPY,Is another S&P 500 change on the horizon? Here...,marketwatch.com,https://www.marketwatch.com/story/is-another-s...
2025-07-30 11:31:03,SPY,EWU: Why UK Stocks Could Beat The S&P 500 The ...,seekingalpha.com,https://seekingalpha.com/article/4806067-ewu-w...
2025-07-30 10:10:35,SPY,"NASDAQ Index, S&P 500 and Dow Jones Forecasts ...",fxempire.com,https://www.fxempire.com/forecasts/article/nas...
2025-07-30 10:05:00,SPY,"S&P 500 inches up on strong GDP; Microsoft, Me...",proactiveinvestors.com,https://www.proactiveinvestors.com/companies/n...
2025-07-30 07:55:50,SPY,State Street Gives Sector Investors an Income ...,etftrends.com,https://www.etftrends.com/state-street-gives-s...
2025-07-30 06:26:54,SPY,SPXL: A Good Option For Investors Looking To A...,seekingalpha.com,https://seekingalpha.com/article/4805923-spxl-...
2025-07-29 12:01:18,SPY,5 ETFs With Big Inflows Last Week on S&P 500's...,zacks.com,https://www.zacks.com/stock/news/2634169/5-etf...
2025-07-29 09:57:44,SPY,"How To Trade SPY, Top Tech Stocks Using Techni...",benzinga.com,https://www.benzinga.com/markets/equities/25/0...
2025-07-29 09:31:21,SPY,"NASDAQ Index, S&P 500 and Dow Jones Forecasts ...",fxempire.com,https://www.fxempire.com/forecasts/article/nas...
2025-07-29 03:59:00,SPY,Stock Market Today: S&P 500 Futures Edge Up an...,wsj.com,https://www.wsj.com/livecoverage/stock-market-...
2025-07-28 23:36:36,SPY,"Bitcoin is the S&P 500 of the future, and will...",youtube.com,https://www.youtube.com/watch?v=lVUbcv8MuzM
2025-07-28 18:02:06,SPY,"S&P 500 notches record close, DOJ to crack dow...",youtube.com,https://www.youtube.com/watch?v=O4cCw22QRSA